-- SEC_ID 1000

INSERT INTO [dbo].[T_OVERRIDE_SECURITY_EXPIRY]
           ([TOP_LEVEL_RUN_ID]
           ,[MASTER_TOP_LEVEL_RUN_ID]
           ,[SEC_ID]
           ,[APIR_IDENTIFICATION_CODE]
           ,[ASSET_TYPE]
           ,[BLOOMBERG_COMPANY_ID]
           ,[BLOOMBERG_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_EXCHANGE_CODE]
           ,[BLOOMBERG_GLOBAL_COMPANY_ID]
           ,[BLOOMBERG_GLOBAL_COMPANY_NAME]
           ,[BLOOMBERG_GLOBAL_ID]
           ,[BLOOMBERG_GLOBAL_SHARE_CLASS_ID]
           ,[BLOOMBERG_INDUSTRY_GROUP_CODE]
           ,[BLOOMBERG_INDUSTRY_GROUP_NAME]
           ,[BLOOMBERG_INDUSTRY_SECTOR_CODE]
           ,[BLOOMBERG_INDUSTRY_SECTOR_NAME]
           ,[BLOOMBERG_INDUSTRY_SUBGROUP_CODE]
           ,[BLOOMBERG_INDUSTRY_SUBGROUP_NAME]
           ,[BLOOMBERG_ISSUE_COUNTRY_CODE]
           ,[BLOOMBERG_MARKET_SECTOR_DESCRIPTION]
           ,[BLOOMBERG_MARKET_STATUS]
           ,[BLOOMBERG_MTF_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_MTF_PRIMARY_GLOBAL_ID]
           ,[BLOOMBERG_PARENT_COMPANY_ID]
           ,[BLOOMBERG_PRIMARY_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_PRIMARY_SECURITY_FLAG]
           ,[BLOOMBERG_PRIMARY_SECURITY_ID]
           ,[BLOOMBERG_PRIMARY_UNDERLYING_GLOBAL_ID]
           ,[BLOOMBERG_SECURITY_ID]
           ,[BLOOMBERG_UNDERLYING_GLOBAL_ID]
           ,[BLOOMBERG_UNIQUE_ID]
           ,[CLASSIFICATION_FINANCIAL_INSTRUMENTS_CODE]
           ,[COMMON_NUMBER]
           ,[COUNTRY_CALENDAR_CODE]
           ,[CUSIP]
           ,[DAYS_TO_SETTLE]
           ,[DOMICILE_ISO_COUNTRY_CODE]
           ,[EFFECTIVE_DATE]
           ,[EXCHANGE_CALENDAR_CODE]
           ,[FILE_NAME]
           ,[IDENTIFIER_NUMBER_DESCRIPTION]
           ,[INCORPORATION_ISO_COUNTRY_CODE]
           ,[IS_REMOVED_BLOOMBERG]
           ,[ISIN]
           ,[ISSUE_ISO_COUNTRY_CODE]
           ,[LOCAL_EXCHANGE_SYMBOL]
           ,[MIC_EXCHANGE_LOCAL_CODE]
           ,[MIC_EXCHANGE_PRIMARY_CODE]
           ,[NAICS_CODE]
           ,[PAR_AMOUNT]
           ,[PAR_VALUE_CCY]
           ,[PARENT_COMPANY_NAME]
           ,[PARENT_COMPANY_TICKER]
           ,[PARENT_INDUSTRY_GROUP]
           ,[PARENT_INDUSTRY_SECTOR]
           ,[PARENT_INDUSTRY_SUBGROUP]
           ,[POST_EURO_ISIN]
           ,[POST_EURO_PAR_AMOUNT]
           ,[POST_EURO_REDOMINATION_CCY]
           ,[PRE_EURO_ISIN]
           ,[PRE_EURO_PAR_AMOUNT]
           ,[PRE_EURO_REDOMINATION_CCY]
           ,[PRICING_FEED_SOURCE_CODE]
           ,[PRIMARY_EXCHANGE_CODE]
           ,[PRIMARY_EXCHANGE_NAME]
           ,[PRIVATE_PLACEMENT_INDICATOR]
           ,[QUOTE_LOT_SIZE]
           ,[REDENOMIATION_ROUNDING_METHOD]
           ,[REDENOMINATION_DATE]
           ,[REDENOMINATION_METHOD]
           ,[REGION_CODE]
           ,[ROUND_LOT_SIZE]
           ,[RULE_144A_INDICATOR]
           ,[SECURITY_DESCRIPTION]
           ,[CURRENCY_ISO_CODE]
           ,[SECURITY_NAME]
           ,[SECURITY_RESTRICTION]
           ,[SECURITY_SHORTNAME]
           ,[SECURITY_TYPE]
           ,[SECURITY_TYPE_DESCRIPTION]
           ,[SEDOL]
           ,[SEDOL_ISO_COUNTRY_CODE]
           ,[SEDOL2]
           ,[SEDOL2_ISO_COUNTRY_CODE]
           ,[SETTLEMENT_CALENDAR_CODE]
           ,[STANDARD_INDUSTRIAL_CLASSIFICATION_CODE]
           ,[STANDARD_INDUSTRIAL_CLASSIFICATION_NAME]
           ,[STATE_CODE]
           ,[TICKER]
           ,[TICKER_AND_EXCHANGE_CODE]
           ,[TRADE_LOT_SIZE]
           ,[TRADING_SYSTEM_IDENTIFIER]
           ,[TRADING_SYSTEM_IDENTIFIER_NAME]
           ,[VALOREN]
           ,[WERTPAPIER]
           ,[WHEN_ISSUED_FLAG]
           ,[CADIS_SYSTEM_INSERTED]
           ,[CADIS_SYSTEM_UPDATED]
           ,[CADIS_SYSTEM_CHANGEDBY]
           ,[CADIS_SYSTEM_PRIORITY]
           ,[CADIS_SYSTEM_LASTMODIFIED]
		)
     VALUES
           ('2018-01-01'
           ,'2018-01-01'
           ,1000
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,'2018-01-01'
           ,GETDATE()
           ,GETDATE()
           ,'TEST'
           ,1
           ,GETDATE()
		)

-- SEC_ID 1001

INSERT INTO [dbo].[T_OVERRIDE_SECURITY_EXPIRY]
           ([TOP_LEVEL_RUN_ID]
           ,[MASTER_TOP_LEVEL_RUN_ID]
           ,[SEC_ID]
           ,[APIR_IDENTIFICATION_CODE]
           ,[ASSET_TYPE]
           ,[BLOOMBERG_COMPANY_ID]
           ,[BLOOMBERG_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_EXCHANGE_CODE]
           ,[BLOOMBERG_GLOBAL_COMPANY_ID]
           ,[BLOOMBERG_GLOBAL_COMPANY_NAME]
           ,[BLOOMBERG_GLOBAL_ID]
           ,[BLOOMBERG_GLOBAL_SHARE_CLASS_ID]
           ,[BLOOMBERG_INDUSTRY_GROUP_CODE]
           ,[BLOOMBERG_INDUSTRY_GROUP_NAME]
           ,[BLOOMBERG_INDUSTRY_SECTOR_CODE]
           ,[BLOOMBERG_INDUSTRY_SECTOR_NAME]
           ,[BLOOMBERG_INDUSTRY_SUBGROUP_CODE]
           ,[BLOOMBERG_INDUSTRY_SUBGROUP_NAME]
           ,[BLOOMBERG_ISSUE_COUNTRY_CODE]
           ,[BLOOMBERG_MARKET_SECTOR_DESCRIPTION]
           ,[BLOOMBERG_MARKET_STATUS]
           ,[BLOOMBERG_MTF_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_MTF_PRIMARY_GLOBAL_ID]
           ,[BLOOMBERG_PARENT_COMPANY_ID]
           ,[BLOOMBERG_PRIMARY_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_PRIMARY_SECURITY_FLAG]
           ,[BLOOMBERG_PRIMARY_SECURITY_ID]
           ,[BLOOMBERG_PRIMARY_UNDERLYING_GLOBAL_ID]
           ,[BLOOMBERG_SECURITY_ID]
           ,[BLOOMBERG_UNDERLYING_GLOBAL_ID]
           ,[BLOOMBERG_UNIQUE_ID]
           ,[CLASSIFICATION_FINANCIAL_INSTRUMENTS_CODE]
           ,[COMMON_NUMBER]
           ,[COUNTRY_CALENDAR_CODE]
           ,[CUSIP]
           ,[DAYS_TO_SETTLE]
           ,[DOMICILE_ISO_COUNTRY_CODE]
           ,[EFFECTIVE_DATE]
           ,[EXCHANGE_CALENDAR_CODE]
           ,[FILE_NAME]
           ,[IDENTIFIER_NUMBER_DESCRIPTION]
           ,[INCORPORATION_ISO_COUNTRY_CODE]
           ,[IS_REMOVED_BLOOMBERG]
           ,[ISIN]
           ,[ISSUE_ISO_COUNTRY_CODE]
           ,[LOCAL_EXCHANGE_SYMBOL]
           ,[MIC_EXCHANGE_LOCAL_CODE]
           ,[MIC_EXCHANGE_PRIMARY_CODE]
           ,[NAICS_CODE]
           ,[PAR_AMOUNT]
           ,[PAR_VALUE_CCY]
           ,[PARENT_COMPANY_NAME]
           ,[PARENT_COMPANY_TICKER]
           ,[PARENT_INDUSTRY_GROUP]
           ,[PARENT_INDUSTRY_SECTOR]
           ,[PARENT_INDUSTRY_SUBGROUP]
           ,[POST_EURO_ISIN]
           ,[POST_EURO_PAR_AMOUNT]
           ,[POST_EURO_REDOMINATION_CCY]
           ,[PRE_EURO_ISIN]
           ,[PRE_EURO_PAR_AMOUNT]
           ,[PRE_EURO_REDOMINATION_CCY]
           ,[PRICING_FEED_SOURCE_CODE]
           ,[PRIMARY_EXCHANGE_CODE]
           ,[PRIMARY_EXCHANGE_NAME]
           ,[PRIVATE_PLACEMENT_INDICATOR]
           ,[QUOTE_LOT_SIZE]
           ,[REDENOMIATION_ROUNDING_METHOD]
           ,[REDENOMINATION_DATE]
           ,[REDENOMINATION_METHOD]
           ,[REGION_CODE]
           ,[ROUND_LOT_SIZE]
           ,[RULE_144A_INDICATOR]
           ,[SECURITY_DESCRIPTION]
           ,[CURRENCY_ISO_CODE]
           ,[SECURITY_NAME]
           ,[SECURITY_RESTRICTION]
           ,[SECURITY_SHORTNAME]
           ,[SECURITY_TYPE]
           ,[SECURITY_TYPE_DESCRIPTION]
           ,[SEDOL]
           ,[SEDOL_ISO_COUNTRY_CODE]
           ,[SEDOL2]
           ,[SEDOL2_ISO_COUNTRY_CODE]
           ,[SETTLEMENT_CALENDAR_CODE]
           ,[STANDARD_INDUSTRIAL_CLASSIFICATION_CODE]
           ,[STANDARD_INDUSTRIAL_CLASSIFICATION_NAME]
           ,[STATE_CODE]
           ,[TICKER]
           ,[TICKER_AND_EXCHANGE_CODE]
           ,[TRADE_LOT_SIZE]
           ,[TRADING_SYSTEM_IDENTIFIER]
           ,[TRADING_SYSTEM_IDENTIFIER_NAME]
           ,[VALOREN]
           ,[WERTPAPIER]
           ,[WHEN_ISSUED_FLAG]
           ,[CADIS_SYSTEM_INSERTED]
           ,[CADIS_SYSTEM_UPDATED]
           ,[CADIS_SYSTEM_CHANGEDBY]
           ,[CADIS_SYSTEM_PRIORITY]
           ,[CADIS_SYSTEM_LASTMODIFIED]
		)
     VALUES
           ('2099-01-01'
           ,'2099-01-01'
           ,1001
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,'2099-01-01'
           ,GETDATE()
           ,GETDATE()
           ,'TEST'
           ,1
           ,GETDATE()
		)

-- SEC_ID 1002

INSERT INTO [dbo].[T_OVERRIDE_SECURITY_EXPIRY]
           ([TOP_LEVEL_RUN_ID]
           ,[MASTER_TOP_LEVEL_RUN_ID]
           ,[SEC_ID]
           ,[APIR_IDENTIFICATION_CODE]
           ,[ASSET_TYPE]
           ,[BLOOMBERG_COMPANY_ID]
           ,[BLOOMBERG_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_EXCHANGE_CODE]
           ,[BLOOMBERG_GLOBAL_COMPANY_ID]
           ,[BLOOMBERG_GLOBAL_COMPANY_NAME]
           ,[BLOOMBERG_GLOBAL_ID]
           ,[BLOOMBERG_GLOBAL_SHARE_CLASS_ID]
           ,[BLOOMBERG_INDUSTRY_GROUP_CODE]
           ,[BLOOMBERG_INDUSTRY_GROUP_NAME]
           ,[BLOOMBERG_INDUSTRY_SECTOR_CODE]
           ,[BLOOMBERG_INDUSTRY_SECTOR_NAME]
           ,[BLOOMBERG_INDUSTRY_SUBGROUP_CODE]
           ,[BLOOMBERG_INDUSTRY_SUBGROUP_NAME]
           ,[BLOOMBERG_ISSUE_COUNTRY_CODE]
           ,[BLOOMBERG_MARKET_SECTOR_DESCRIPTION]
           ,[BLOOMBERG_MARKET_STATUS]
           ,[BLOOMBERG_MTF_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_MTF_PRIMARY_GLOBAL_ID]
           ,[BLOOMBERG_PARENT_COMPANY_ID]
           ,[BLOOMBERG_PRIMARY_COMPOSITE_GLOBAL_ID]
           ,[BLOOMBERG_PRIMARY_SECURITY_FLAG]
           ,[BLOOMBERG_PRIMARY_SECURITY_ID]
           ,[BLOOMBERG_PRIMARY_UNDERLYING_GLOBAL_ID]
           ,[BLOOMBERG_SECURITY_ID]
           ,[BLOOMBERG_UNDERLYING_GLOBAL_ID]
           ,[BLOOMBERG_UNIQUE_ID]
           ,[CLASSIFICATION_FINANCIAL_INSTRUMENTS_CODE]
           ,[COMMON_NUMBER]
           ,[COUNTRY_CALENDAR_CODE]
           ,[CUSIP]
           ,[DAYS_TO_SETTLE]
           ,[DOMICILE_ISO_COUNTRY_CODE]
           ,[EFFECTIVE_DATE]
           ,[EXCHANGE_CALENDAR_CODE]
           ,[FILE_NAME]
           ,[IDENTIFIER_NUMBER_DESCRIPTION]
           ,[INCORPORATION_ISO_COUNTRY_CODE]
           ,[IS_REMOVED_BLOOMBERG]
           ,[ISIN]
           ,[ISSUE_ISO_COUNTRY_CODE]
           ,[LOCAL_EXCHANGE_SYMBOL]
           ,[MIC_EXCHANGE_LOCAL_CODE]
           ,[MIC_EXCHANGE_PRIMARY_CODE]
           ,[NAICS_CODE]
           ,[PAR_AMOUNT]
           ,[PAR_VALUE_CCY]
           ,[PARENT_COMPANY_NAME]
           ,[PARENT_COMPANY_TICKER]
           ,[PARENT_INDUSTRY_GROUP]
           ,[PARENT_INDUSTRY_SECTOR]
           ,[PARENT_INDUSTRY_SUBGROUP]
           ,[POST_EURO_ISIN]
           ,[POST_EURO_PAR_AMOUNT]
           ,[POST_EURO_REDOMINATION_CCY]
           ,[PRE_EURO_ISIN]
           ,[PRE_EURO_PAR_AMOUNT]
           ,[PRE_EURO_REDOMINATION_CCY]
           ,[PRICING_FEED_SOURCE_CODE]
           ,[PRIMARY_EXCHANGE_CODE]
           ,[PRIMARY_EXCHANGE_NAME]
           ,[PRIVATE_PLACEMENT_INDICATOR]
           ,[QUOTE_LOT_SIZE]
           ,[REDENOMIATION_ROUNDING_METHOD]
           ,[REDENOMINATION_DATE]
           ,[REDENOMINATION_METHOD]
           ,[REGION_CODE]
           ,[ROUND_LOT_SIZE]
           ,[RULE_144A_INDICATOR]
           ,[SECURITY_DESCRIPTION]
           ,[CURRENCY_ISO_CODE]
           ,[SECURITY_NAME]
           ,[SECURITY_RESTRICTION]
           ,[SECURITY_SHORTNAME]
           ,[SECURITY_TYPE]
           ,[SECURITY_TYPE_DESCRIPTION]
           ,[SEDOL]
           ,[SEDOL_ISO_COUNTRY_CODE]
           ,[SEDOL2]
           ,[SEDOL2_ISO_COUNTRY_CODE]
           ,[SETTLEMENT_CALENDAR_CODE]
           ,[STANDARD_INDUSTRIAL_CLASSIFICATION_CODE]
           ,[STANDARD_INDUSTRIAL_CLASSIFICATION_NAME]
           ,[STATE_CODE]
           ,[TICKER]
           ,[TICKER_AND_EXCHANGE_CODE]
           ,[TRADE_LOT_SIZE]
           ,[TRADING_SYSTEM_IDENTIFIER]
           ,[TRADING_SYSTEM_IDENTIFIER_NAME]
           ,[VALOREN]
           ,[WERTPAPIER]
           ,[WHEN_ISSUED_FLAG]
           ,[CADIS_SYSTEM_INSERTED]
           ,[CADIS_SYSTEM_UPDATED]
           ,[CADIS_SYSTEM_CHANGEDBY]
           ,[CADIS_SYSTEM_PRIORITY]
           ,[CADIS_SYSTEM_LASTMODIFIED]
		)
     VALUES
           (NULL
           ,NULL
           ,1002
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,GETDATE()
           ,GETDATE()
           ,'TEST'
           ,1
           ,GETDATE()
		)

-- SELECT * FROM dbo.T_OVERRIDE_SECURITY_EXPIRY WHERE SEC_ID BETWEEN 1000 AND 1007

-- DELETE dbo.T_OVERRIDE_SECURITY_EXPIRY WHERE SEC_ID BETWEEN 1000 AND 1007

GO


